import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

var lightTheme = FlexThemeData.light(
  colors: const FlexSchemeColor(
    primary: Color(0xff4c9bba),
    primaryContainer: Color(0xff9cebeb),
    secondary: Color(0xffff4f58),
    secondaryContainer: Color(0xffffdad7),
    tertiary: Color(0xff73cd9f),
    tertiaryContainer: Color(0xfffcbdbd),
    appBarColor: Color(0xffffdad7),
    error: Color(0xffb00020),
  ),
  surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
  blendLevel: 22,
  appBarStyle: FlexAppBarStyle.background,
  bottomAppBarElevation: 1.0,
  lightIsWhite: true,
  subThemesData: const FlexSubThemesData(
    useM2StyleDividerInM3: true,
    elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
    elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
    segmentedButtonSchemeColor: SchemeColor.primary,
    inputDecoratorSchemeColor: SchemeColor.primary,
    inputDecoratorBackgroundAlpha: 21,
    inputDecoratorRadius: 8.0,
    inputDecoratorUnfocusedHasBorder: false,
    inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
    fabSchemeColor: SchemeColor.tertiary,
    popupMenuRadius: 6.0,
    popupMenuElevation: 4.0,
    dialogRadius: 20.0,
    dialogElevation: 3.0,
    timePickerDialogRadius: 20.0,
    snackBarBackgroundSchemeColor: SchemeColor.inverseSurface,
    drawerIndicatorSchemeColor: SchemeColor.primary,
    bottomSheetRadius: 20.0,
    bottomSheetElevation: 2.0,
    bottomSheetModalElevation: 3.0,
    bottomNavigationBarMutedUnselectedLabel: false,
    bottomNavigationBarMutedUnselectedIcon: false,
    bottomNavigationBarBackgroundSchemeColor: SchemeColor.surfaceVariant,
    menuRadius: 6.0,
    menuElevation: 4.0,
    menuBarRadius: 0.0,
    menuBarElevation: 1.0,
    navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
    navigationBarMutedUnselectedLabel: false,
    navigationBarSelectedIconSchemeColor: SchemeColor.background,
    navigationBarMutedUnselectedIcon: false,
    navigationBarIndicatorSchemeColor: SchemeColor.primary,
    navigationBarIndicatorOpacity: 1.00,
    navigationBarBackgroundSchemeColor: SchemeColor.background,
    navigationBarElevation: 1.0,
    navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
    navigationRailMutedUnselectedLabel: false,
    navigationRailSelectedIconSchemeColor: SchemeColor.background,
    navigationRailMutedUnselectedIcon: false,
    navigationRailIndicatorSchemeColor: SchemeColor.primary,
    navigationRailIndicatorOpacity: 1.00,
  ),
  keyColors: const FlexKeyColors(
    useSecondary: true,
    useTertiary: true,
    keepPrimary: true,
    keepSecondary: true,
    keepTertiary: true,
  ),
  tones: FlexTones.ultraContrast(Brightness.light)
      .onMainsUseBW()
      .onSurfacesUseBW(),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
);

var darkTheme = FlexThemeData.dark(
  colors: const FlexSchemeColor(
    primary: Color(0xff669db3),
    primaryContainer: Color(0xff078282),
    secondary: Color(0xfffc6e75),
    secondaryContainer: Color(0xff92001a),
    tertiary: Color(0xffa4e4b6),
    tertiaryContainer: Color(0xff80d0b9),
    appBarColor: Color(0xff92001a),
    error: Color(0xffcf6679),
  ),
  surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
  blendLevel: 5,
  appBarStyle: FlexAppBarStyle.background,
  bottomAppBarElevation: 2.0,
  subThemesData: const FlexSubThemesData(
    useM2StyleDividerInM3: true,
    elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
    elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
    segmentedButtonSchemeColor: SchemeColor.primary,
    inputDecoratorSchemeColor: SchemeColor.primary,
    inputDecoratorBackgroundAlpha: 43,
    inputDecoratorRadius: 8.0,
    inputDecoratorUnfocusedHasBorder: false,
    inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
    fabSchemeColor: SchemeColor.tertiary,
    popupMenuRadius: 6.0,
    popupMenuElevation: 4.0,
    dialogRadius: 20.0,
    dialogElevation: 3.0,
    timePickerDialogRadius: 20.0,
    snackBarBackgroundSchemeColor: SchemeColor.inverseSurface,
    drawerIndicatorSchemeColor: SchemeColor.primary,
    bottomSheetRadius: 20.0,
    bottomSheetElevation: 2.0,
    bottomSheetModalElevation: 3.0,
    bottomNavigationBarMutedUnselectedLabel: false,
    bottomNavigationBarMutedUnselectedIcon: false,
    bottomNavigationBarBackgroundSchemeColor: SchemeColor.surfaceVariant,
    menuRadius: 6.0,
    menuElevation: 4.0,
    menuBarRadius: 0.0,
    menuBarElevation: 1.0,
    navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
    navigationBarMutedUnselectedLabel: false,
    navigationBarSelectedIconSchemeColor: SchemeColor.background,
    navigationBarMutedUnselectedIcon: false,
    navigationBarIndicatorSchemeColor: SchemeColor.primary,
    navigationBarIndicatorOpacity: 1.00,
    navigationBarBackgroundSchemeColor: SchemeColor.background,
    navigationBarElevation: 1.0,
    navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
    navigationRailMutedUnselectedLabel: false,
    navigationRailSelectedIconSchemeColor: SchemeColor.background,
    navigationRailMutedUnselectedIcon: false,
    navigationRailIndicatorSchemeColor: SchemeColor.primary,
    navigationRailIndicatorOpacity: 1.00,
  ),
  keyColors: const FlexKeyColors(
    useSecondary: true,
    useTertiary: true,
    keepTertiaryContainer: true,
    keepSecondary: true,
  ),
  tones: FlexTones.ultraContrast(Brightness.dark),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
);
